### ISSUE TITLE
Unable to upload an image

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/PhotoVault#12]
Steps to recreate:
1. Log in
2. Click on + icon
3. Enter a caption and location in the modal
4. Choose a picture from local storage

At this point, received the following in console:
http://localhost:5000/download?fileId=undefined 404 Not found error and unable to proceed from there
http://localhost:5000/ POST 404 Not found

**Comment by uteerna** [comment]
Thank you for the feedback. We have fixed the issue with the upload image. Please pull the branch again and test it. Please let us know in case you run into any issues with it.

**Comment by aravindparappil46** [comment]
Hi Uteerna,
I was not able to find manage.py in django_test_folder after the pull. Please take a look

**Comment by uteerna** [comment]
Hi Aravind, 
The folder path has changed a bit. In the uploadImages branch there is an upload-images folder which has the new django_test_project. Under this django_test_project, you have manage.py.

**Comment by aravindparappil46** [comment]
Ah got it. Thanks!!

**Comment by aravindparappil46** [comment]
This has been fixed and verified. Closing this issue!!
