### ISSUE TITLE
Peer review assignment 1

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/PhotoVault#13]
Hello Team,
I really liked the following things in PhotoVault application. 
I like the wiki. Steps are nicely documented. It was easy to run the project on local.
I like the simple UI too.
I like the idea of having a backup database as well (as mentioned in the architecture diagram).

However, following are the issues I faced:

1. Create post functionality is not working. Because of this, I am not able to search the image I am trying to upload and post. However, it worked when I searched for the default image "ocean" already present.
2. There is no way to log out of the session. So I could not verify anything related to the session.
3. Clicking on "PhotoVault" present on the menu bar takes me to the signup/login page even when I'm already logged in. Maybe it can redirect me to a default home page or something. I think session management should take care of this.
4. I am getting a lot of 404 errors on every click on any textbox/area.

Please let me know if I misunderstood any of the functionalities. Also, let me know if you need screenshots for any of these issues that I faced.

Good luck!

**Comment by uteerna** [comment]
Hi Shweta, 
Thank you for the feedback.  We have fixed the 404 error that you might be getting when uploading the image. Please check that and let us know if that persists. We are working on the other issues that you have raised and will let you know once they are fixed.

**Comment by uteerna** [comment]
Hi Shweta, 
We have fixed the issues. We have changed the download microservice to explore microservice. Please pull the new branch and follow the wiki for detailed instructions. Please let us know in case you run into any other issues. 
Thanks :)
