### ISSUE TITLE
Keep pycache folders in gitignore

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/PhotoVault#15]
Because certain __pycache__ folders within the django project are pushed to the repo, I get merge conflicts whenever I pull the branch. 

A good way to solve this would be to keep another .gitignore file within the 2nd django_test_project folder

Here is a good sample for a gitignore file for Django projects
https://github.com/jpadilla/django-project-template/blob/master/.gitignore

**Comment by uteerna** [comment]
Thank you for the feedback Aravind.
