### ISSUE TITLE
Peer Review Project Milestone 1

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/PhotoVault#16]
Kudos to you guys! The major issue was fixed very soon and I was able to understand the installation directions really easily. Rest of the improvements are all minor.

Issues linked here:
#18 #17  #12  #15 #19

**Comment by aravindparappil46** [comment]
Checked Issue #18 . It is fixed!

**Comment by uteerna** [comment]
Hi Aravind, 
Please review if all the issues are fixed.

**Comment by aravindparappil46** [comment]
Everything looks alright now! Great job!
