### ISSUE TITLE
CORS error on viewing images

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/PhotoVault#17]
OPTIONS http://localhost:8080/api/fileOps 403

Access to XMLHttpRequest at 'http://localhost:8080/api/fileOps' from origin 'http://localhost:3000

Getting the following error when clicking on Explore Public Images and My Gallery.

Must have something to do with ALLOW_CORS_ORIGINS setup

**Comment by vrishalibhor** [comment]
Hi Aravind,

We have fixed this issue. It would be great if you review it and revert.

**Comment by aravindparappil46** [comment]
Will do.
Also, it'd be great if all commit messages followed this format:
"#<issue_number>:   <usual_commit_message>"

Advantage of this is that the commit gets automatically referenced to the issue and can be viewed in the respective Issue's page

**Comment by uteerna** [comment]
Thank you, Aravind. Will keep this in mind.

**Comment by vrishalibhor** [comment]
Hi Aravind, Please read the wiki again and then review.
We have changed the download microservice to explore microservice

**Comment by aravindparappil46** [comment]
Works for me! Great!
