### ISSUE TITLE
Previous text box inputs being retained

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/PhotoVault#18]
When I upload an image and provide caption and location, they are not being cleared when I try to upload another image.

Steps to reproduce:
1. Log in
2. Click on +
3. Enter some value for both text fields
4. Choose an image and click Upload
5. Again click on +

At this point, you can see the values entered at Step 3 in the text fields (pre-filled). This should be emptied.

**Comment by vrishalibhor** [comment]
Thanks for pointing out the bug, Aravind. I have fixed it and pushed the changes. Please verify the same.

**Comment by aravindparappil46** [comment]
Please link commits to issues :) It'll be easier to identify which commit was for this issue
EDIT: My bad. You had referenced the umbrella issue for Peer Review Project 1 instead! Thanks!
