### ISSUE TITLE
Modal pops up only on hitting the +

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/PhotoVault#19]
While uploading an image, I have to click  exactly on the plus icon to show the modal. Clicking around on the blue area doesn't trigger the same.

I believe this is due to the onClick being on the _+_ icon instead of the enclosing Button tag

**Comment by vrishalibhor** [comment]
Hi Aravind, excellent observation :)
I have pushed the changes. Please review.

**Comment by aravindparappil46** [comment]
Looks great! Closing this!
