### ISSUE TITLE
Peer Review - Milestone 1

### ISSUE THREAD

**Issue by ameyarangal** [airavata-courses/PhotoVault#20]
Hi Team,

I think the idea of the project is very good and UI is impressive. 
Wiki is nicely updated and have all necessary information.
I was able to setup the branches and services properly.

I was having following issue while accessing the application:
1. After uploading the image I was getting 200 OK response, but the uploaded images was not displaying on search.
2. Gallery page is not displaying the uploaded images.
3. After clicking Gallery page button I am getting 403 response.
4. Explore Public page button also gives 403 response.
5. Navigating successfully to /gallery directly without login.
6. If there are image size restrictions, could you please mention that on the upload pop-up.

Please let me know if you need any further information.

Thanks,
Ameya

**Comment by vrishalibhor** [comment]
Hi Ameya,

Thank you for your comments.
We have fixed the following issues:
* After uploading the image I was getting 200 OK response, but the uploaded images was not displaying on search.
* Gallery page is not displaying the uploaded images.
* After clicking Gallery page button I am getting 403 response.
* Explore Public page button also gives 403 response

Please review them.

Thanks :)

**Comment by uteerna** [comment]
Hi Ameya, 
Please read the wiki again when testing. We have changed a microservice from download to explore. Thank you.

**Comment by ameyarangal** [comment]
I have checked the above issues, all are working fine. 

I have raised  #23 for point number 5.

Thanks
