### ISSUE TITLE
Assignment 1 grading

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/PhotoVault#25]
Hi Team,

I am downloading the pre-requisites to start the project. Can you please update the wik with the steps to install Node.js v11.6. The mentioned link redirects to download page of v11.10.0. If the version doesn't matter let me know if I can continue with v11.10.0.

Regards,
Raghottam

**Comment by raghu2094** [comment]
I can see a lot of dependencies being installed using pip. Please mention all the dependencies to be installed in a .txt file and push it to the respective branch. Will be easier while installing.

**Comment by raghu2094** [comment]
Hi @uteerna  @mkhambat  and @vrishalibhor ,

I have completed reviewing your project. Good job on the work done so far. However there are few things which you need to work on:
1) The search functionality is broken. Unable to search images using the caption in gallery.
2) Even after not making the photo public, the image can be seen under explore images
3) The metadata of the uploaded image is not being saved in your database.

On the documentation front, I found that the wiki has not been updated with working of each microservice. Describe in brief the functionality of  each microservice and how it is being achieved.
The architecture diagram doesn't represent where the images are being uploaded. Make sure to have clear instructions for installing/starting each microservice.
I can see all the microservices present on the master branch. Please make sure to keep each microservice on a different branch. 
 
I would suggest working on the fixes ASAP before starting with implementation of any new feature. Setting the foundation is essential before moving on to other assignments which would involve much complex tasks.

Regards,
Raghottam

**Comment by uteerna** [comment]
@raghu2094 We have fixed the issues. Please check and let us know in case we missed something.

**Comment by raghu2094** [comment]
Hi Team,
I have verified again. All services are working fine now.
