### ISSUE TITLE
jenkins free style jobs duplication

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/PhotoVault#37]
Good job setting Jenkins up.
But when i tried a test commit to one of the branch, i could see two jobs trigger at the same time.
When i looked into the configuration, i could see two jobs doing the same thing, pointing to the same  feature job.
Am i missing something which is left out from the wiki?

**Comment by vrishalibhor** [comment]
Hi Deepak,
Yes, we have an API gateway that routes requests to the specific microservice. As of now, the code for API gateway is included in the loginSearch branch, however, we intend to separate it out from the loginSearch branch in the future.
