### ISSUE TITLE
Unable to See public images once i upload a image.

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/PhotoVault#39]
Hi Team,

A very good job on the Ui and the layout of the components.
When i tried, reverting back to the public images, since i included the image i uploaded in public image. I could not see anything in the public image tab.

**Comment by uteerna** [comment]
Hi @deepakh2810, I am not sure why you are facing that issue. I also created a new user and replicated what you have done and I did not face any such issues. Can you please verify again? I have attached the screenshot of the Explore Public Images tab which I clicked after uploading the image.
<img width="1440" alt="screen shot 2019-03-03 at 11 13 18 pm" src="https://user-images.githubusercontent.com/31369347/53710210-1d14ac80-3e0a-11e9-987b-26b298aeb4e3.png">
