### ISSUE TITLE
Peer Review Milestone 2 

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/PhotoVault#41]
Great job in completing Milestone 2. Here are a few things that i noticed:
•	Having gone through the CI/CD, the connection of Jenkins master to the slaves seems good. But I could see two jobs being duplicated and doing the same thing. 
 •	Also, I would suggest going ahead the free style jobs in Jenkins can be made individual pipelines with separation of build, running test cases and Deployment.  
•	Service Discovery with consul looks great. But a little bit more of information in wiki would have helped me understand this easily and better. 
•	You guys could have included an architecture diagram of how things are working with the introduction of Consul which would have helped the user to understand. 
•	Another suggestion would be to dockerize the services in instances since it would remove manual installation or running scripts for the same through Jenkins. Doing this we could also deliver binaries for your services to users to use them, as images by ensuring they are tagged with the latest code.

Best,
Deepak Hanumanthaiah

**Comment by uteerna** [comment]
Hi Deepak,
Thank you for the suggestions. We will keep that in mind for the next milestone. Also, Docker will be implemented as part of next milestone as specified by the AI's and we will be implementing it then. We will update the architecture diagram by tomorrow.
