### ISSUE TITLE
Review for Assignment 2

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/PhotoVault#42]
Hey Team, 
I was about to start the review for assignment2. 
Please share your Jenkins credentials with me on Slack.

**Comment by nawazkh** [comment]
Hey Team, I am unable to log into the website. There are no logs/errors shown to me about the login. Please guide me here.

**Comment by nawazkh** [comment]
Hey Team, I am facing issues in logging in and viewing the image after upload. Can you please share the logs of this issue? or help me with the issue?

**Comment by uteerna** [comment]
Hi Nawaz, 
The server was off since we are working on Milestone 3 as well. It should all work fine now. Please review and let us know.

**Comment by nawazkh** [comment]
Hey Team, I am sorry I forgot to share my feedback, so here it goes.
 
There were few things missing at the time of grading of assignment 2, I have listed them below:
1. I did not find any test cases in your modules, please do write test cases for your modules so that continuous integration shows right results.
2. The services were being built on the same instance where they were being deployed. IMO, there should be one dev environment used to build a system and deploy it to production servers. Please do implement that.
3. Documentation pertaining to Assignment 2 was not very detailed. Please mention the tasks achieved using zookeeper and the steps zookeeper does to support your system.
4. We are also looking for functionality improvement, so if there was any functionality improved over as the part of sprints, do include it in your wiki.
 
However, I really like the project concept and the work put behind it. Keep up the good work!
