### ISSUE TITLE
[FRONT END] signup doesn't work

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/PhotoVault#57]
I tried to signup from the UI.

after clicking on Submit, i could not see anything happening.

![image](https://user-images.githubusercontent.com/42894144/55506429-67649580-5623-11e9-8a99-31ecd13966a6.png)

There are no console errors, however, the request to  http://149.165.157.198:30002 web service shows a `204 no content` status, and the response is empty.

![image](https://user-images.githubusercontent.com/42894144/55506543-ad215e00-5623-11e9-8e84-07567fae5ece.png)

![image](https://user-images.githubusercontent.com/42894144/55506559-b8748980-5623-11e9-89d0-8ed18b28019b.png)

**Comment by vrishalibhor** [comment]
Hi Shashank,

Thanks for bringing this issue to our notice. We have fixed it.
You may test this.

Thanks.
