### ISSUE TITLE
[JENKINS] suggestion to simplify automation of microservices deployment

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/PhotoVault#58]
I saw a groovy script in nodepipeline that tells jenkins master to SSH into kubernetes master, and run a script there, that builds docker image, uploads it on DockerHub and then instructs kuberctl to deploy microservices.

The pipeline and jobs run fine, but all this can be done using jenkins inbuilt features, no need to write fat groovy scripts.

Add kube master as a slave to jenkins master, instead of pipeline, use a job that makes use of github webhook to clone project and checkout branches. if you do this, you wont need to write scripts to ssh to kube master.

then write docker commands and kubectl related commands that will deploy containers.

**Comment by uteerna** [comment]
Thank you for your feedback. We will keep that in mind in the future.
