### ISSUE TITLE
[SUMMARY] summary of milestone 3 peer review

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/PhotoVault#59]
guys, it's evident that you have invested much time and effort in achieving milestone 3. 
- UI is simple, consistent and elegant.
- Kubernetes cluster works fine, system is fault tolerant, and jmeter stats show that load balancing works.
- there was some issue in signup, you should write test cases for critical functionality that will notify you when the test cases fail.
- jenkins configurations can be much more simplified.

https://github.com/airavata-courses/PhotoVault/issues/58
https://github.com/airavata-courses/PhotoVault/issues/57

**Comment by uteerna** [comment]
Hi Shashank, 

Thank you for your feedback. We have fixed the issue with "register". We will also keep your feedback in mind.

Thanks,
Uteerna
