### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/PhotoVault#60]
When I create a post and submit it, the page does not refresh hence I cannot see my newly uploaded image immediately. When I try to refresh the page, it redirects me to the login page. When I try to debug it, it prints user name and first name both to be "null"

**Comment by uteerna** [comment]
Hi Shweta, 

In order to see the uploaded image you have to click on My Gallery to see the uploaded image. Auto refresh is not done for upload.

Thanks, 
Uteerna

**Comment by kulsv** [comment]
Hi Uteerna,
Yes clicking on the tabs works. However, it'd be nice to auto refresh it and avoid re-logging in on manual refresh.
However, I see that you've mentioned to add this in future so closing this issue.
