### ISSUE TITLE
Peer review for milestone 3

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/PhotoVault#61]
Hello Team,
I like the thorough explanation given in the Wiki. It helped a lot to review the system quickly.
I raised the issue #60 for a small UI bug.
I pushed dummy commits to all the develop branches mentioned in Wiki and all Jenkins jobs ran fine. I was able to access the system after each of those builds succeeded.
In wiki, the JMeter images are not accessible. The link provided is not working for some reason.
I have not yet tested the Kubernetes part yet. Please let me know if Kubemonkey is running already. And it'd be great if you'd guide me on how to test the Kubernetes part using Kubemonkey as I am not aware of Kubemonkey's interface.
I'll be editing this issue again, once I'm done with testing the Kubernetes.

**Comment by uteerna** [comment]
Hi Shweta, 

Thank you for your feedback. For the UI issue, if you click on My Gallery after posting an image then you will be able to see the uploaded image. We don't have auto-refresh on that page right now but we will implement it in future. For the Kube Monkey part please use the following commands to test it.
```watch kubectl logs kube-monkey-65b58769d4-7qcm8  -n kube-system (kube-monkey-65b58769d4-7qcm8 - this is the id of the kube-monkey pod)```
```watch kubectl get pods```
Master IP: 149.165.157.198
Please use this on two different terminal windows to see things simultaneously.
I have also updated the link for JMeter results in the wiki.

Thanks, 
Uteerna

**Comment by kulsv** [comment]
Hi Uteerna,
Thanks for getting back on all my queries.
I have tested Kubernetes using Kubemonkey and things seem to be working fine.
Good job!

Closing this issue.
-
Shweta
