### ISSUE TITLE
Peer review: Architectural query/suggestion

### ISSUE THREAD

**Issue by jkumar10** [airavata-courses/PhotoVault#79]
Hi team,
In the wiki you have mentioned that the kubernetes cluster has 10 pods for each service, 5 G and 5 B. So are you spreading a single Kubernetes cluster across IU and TACC or they are the separate clusters? I feel spreading cluster across data centers is not a good idea. Correct me if I am wrong. Also, Its better to update the architecture diagram as well on the same page of the release instructions. This way I don't have to switch while reading and understanding the architecture.

**Comment by mkhambat** [comment]
Hi Jainendra,
We have 10 pods on IU and the other 10 pods on TACC. Therefore, we are not spreading the kubernetes cluster across both the data centers. Each data center has it's own kubernetes master and slaves.
