### ISSUE TITLE
Peer Review - Milestone 4

### ISSUE THREAD

**Issue by arbansal** [airavata-courses/PhotoVault#81]
Could you please share the Jenkins credentials with me for peer review (arbansal@iu.edu)

**Comment by arbansal** [comment]
Below are my review comments:
- UI looks impressive and is very user-friendly and easy to navigate through.
- Implementation of HAProxy for high availability and implementation of Blue-Green Deployment looks good!
- Verified that the Kubernetes fault tolerance is working just fine as well.
Great job overall!

**Comment by uteerna** [comment]
Hi Arpit,
Thank you for your feedback.

**Comment by mkhambat** [comment]
Hi Arpit,
I believe that the credentials are sent to you via email.
Also, thanks for the comments.
