### ISSUE TITLE
Peer review Summary: Milestone 4

### ISSUE THREAD

**Issue by jkumar10** [airavata-courses/PhotoVault#82]
Hello Team, 

Kudos for completing the milestone 4. Photo upload, search and explore public images functionality seems to work fine. However there were some latency issues that I seem to face in the UI. Overall UI looks good.

Oauth/OpenID connect is not yet implemented so please work on that.

I had an architectural query with Kubernetes which I have mentioned in issue #79.
But I can see that you have provided two Kubernetes cluster dashboards for IU and TACC so I feel this is the correct approach. I am not able to open the dashboards as it is asking me for the token. (Issue #78) Once you provide that I will verify it.

I have checked the Jenkins pipeline which seem to be implemented fine with separate jobs for Blue and Green deployment, however I am not able to check and verify the implementation of Kubemonkey. My  suggestion is to add steps in the wiki to verify that or provide some results/screenshots. Architectural implementation of HA Proxy looks fine to me.

Overall architectural diagram and wiki could have been more detailed and both could have been on the same page. Finally, overall project looks good to me in both UI/functionality aspect and distributed micro-service architecture.

**Comment by jkumar10** [comment]
I got the Kubernetes token in mail ! Thanks.

**Comment by uteerna** [comment]
Hi @jkumar10, 

Thank you for your feedback.  To check Kubemonkey, we will need to add your ssh key to the server. Kubemonkey was a part of milestone 3 so we have specified its functionality in that. Please provide your ssh key and use `watch kubectl get pods` to see how pods are deleted and created immediately. Also please let us know what additional details would you like to see in the architecture diagram and wiki so we could improve on them in the remaining time.

Thanks, 
Uteerna

**Comment by jkumar10** [comment]
I have checked and verified creation and deletion of pods. It seems to be working fine.
