### ISSUE TITLE
Peer Review - Milestone 4

### ISSUE THREAD

**Issue by vanessapinto257** [airavata-courses/PhotoVault#84]
Hi guys,

Just started the peer review. I tried to log in through google but I got the following error:

![Screen Shot 2019-04-26 at 10 27 48 PM](https://user-images.githubusercontent.com/43382508/56843731-1e46e080-6873-11e9-9b71-6c0f93785e39.png)

Also, when you try to go back from the social login page, it doesn't happen on the first try.

**Comment by mkhambat** [comment]
Hi Venessa,
I works for us, can you try it using incognito mode once? Please see the image below when we try to login in incognito mode.
<img width="1440" alt="Screen Shot 2019-04-28 at 3 07 59 PM" src="https://user-images.githubusercontent.com/31369347/56868954-8e667b00-69c7-11e9-9737-5d1b0a076eae.png">
Regards,
Murtaza Khambaty.

**Comment by vanessapinto257** [comment]
Thanks, it works in incognito mode.

UI looks really good. 
I like the search functionality based on the caption. 
The CI/CD is working smoothly.

Great job!
